import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const helvetica = localFont({
  src: [
    {
      path: './fonts/HelveticaNeueMedium.otf',
      weight: '500',
      style: 'normal'
    },

    {
      path: './fonts/HelveticaNeueHeavy.otf',
      weight: '800',
      style: 'normal'
    },

    {
      path: './fonts/HelveticaNeueLight.otf',
      weight: '300',
      style: 'normal'
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${helvetica.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
